# Generated by Django 5.2.6 on 2025-10-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Customer', 'customer'), ('Student', 'student'), ('Ownner', 'ownner')], default='Customer', max_length=10)),
            ],
        ),
    ]
