# Generated by Django 5.2.6 on 2025-10-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='food',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
