# Generated by Django 5.2.6 on 2025-10-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('returante', '0002_remove_order_food_remove_order_user_delete_supply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.ImageField(blank=True, null=True, upload_to='sample/')),
                ('title', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('selection', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('snack', 'Snack')], default='Foods', max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
