# Generated by Django 5.2.6 on 2025-10-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returante', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('guest_phone_num', models.IntegerField()),
            ],
        ),
    ]
