# Generated by Django 5.2.6 on 2025-10-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returante', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='meassage',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
