# Generated by Django 5.2.6 on 2025-10-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returante', '0005_reservation_meassage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_phone_num',
            field=models.IntegerField(max_length=20),
        ),
    ]
