# Generated by Django 5.2.6 on 2025-10-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returante', '0007_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='KFC Student Group', max_length=100)),
                ('link', models.URLField(default='https://chat.whatsapp.com/XXXXXXXXXXXXXXX', help_text='WhatsApp group invite link for registered students.')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
