# Generated by Django 5.2.6 on 2025-10-17 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returante', '0008_grouplink_alter_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='joined_group_name',
            field=models.ForeignKey(blank=True, help_text='The WhatsApp group this student joined.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='returante.grouplink'),
        ),
        migrations.AddField(
            model_name='student',
            name='whatsapp_joined',
            field=models.BooleanField(default=False),
        ),
    ]
