# Generated by Django 5.2.6 on 2025-10-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returante', '0009_student_joined_group_name_student_whatsapp_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField(max_length=200)),
            ],
        ),
    ]
