# Generated by Django 5.2.6 on 2025-10-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returante', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_phone_num',
            field=models.IntegerField(),
        ),
    ]
