# Generated by Django 5.2.6 on 2025-11-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returante', '0012_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blogs/')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
