# Generated by Django 5.2.6 on 2025-11-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returante', '0013_blogdisplay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdisplay',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
