# Generated by Django 5.2.6 on 2025-11-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returante', '0014_alter_blogdisplay_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='discription',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
