# Generated by Django 5.2.6 on 2025-11-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returante', '0015_menu_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='menu_items',
            field=models.ManyToManyField(blank=True, to='returante.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
