# Generated by Django 5.2.6 on 2025-11-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returante', '0016_reservation_menu_items_alter_menu_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
